#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.3.1
# In conjunction with Tcl version 8.6
#    Oct 29, 2014 04:49:09 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import popup_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    root.title('New_Toplevel_1')
    root.geometry('600x450+650+150')
    w = New_Toplevel_1 (root)
    popup_support.init(root, w)
    root.mainloop()

w = None
def create_New_Toplevel_1(root, param=None):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    w.title('New_Toplevel_1')
    w.geometry('600x450+650+150')
    w_win = New_Toplevel_1 (w)
    popup_support.init(w, w_win, param)
    return w_win

def destroy_New_Toplevel_1():
    global w
    w.destroy()
    w = None


class New_Toplevel_1:
    def __init__(self, master=None):
        _bgcolor = 'wheat'  # X11 color: #f5deb3
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#b2c9f4' # Closest X11 color: 'SlateGray2'
        _ana1color = '#eaf4b2' # Closest X11 color: '{pale goldenrod}'
        _ana2color = '#f4bcb2' # Closest X11 color: 'RosyBrown2'
        font10 = "-family {DejaVu Sans Mono} -size 14 -weight normal  " + \
            "-slant roman -underline 0 -overstrike 0"
        master.configure(background="wheat")
        master.configure(highlightbackground="wheat")
        master.configure(highlightcolor="black")


        self.Button1 = Button (master)
        self.Button1.place(relx=0.23,rely=0.38,height=35,width=103)
        self.Button1.configure(activebackground="#f4bcb2")
        self.Button1.configure(background=_bgcolor)
        self.Button1.configure(disabledforeground="#b8a786")
        self.Button1.configure(font=font10)
        self.Button1.configure(highlightbackground="wheat")
        self.Button1.configure(text='''Button1''')

        if (root.tk.call('tk', 'windowingsystem')=='aqua'):
            self.Button1.bind('<Button-2>', lambda e: self.popup1(e))
            self.Button1.bind('<Control-1>', lambda e: self.popup1(e))
        else:
            self.Button1.bind('<Button-3>', lambda e: self.popup1(e))

        self.Button2 = Button (master)
        self.Button2.place(relx=0.68,rely=0.38,height=35,width=103)
        self.Button2.configure(activebackground="#f4bcb2")
        self.Button2.configure(background=_bgcolor)
        self.Button2.configure(disabledforeground="#b8a786")
        self.Button2.configure(font=font10)
        self.Button2.configure(highlightbackground="wheat")
        self.Button2.configure(text='''Button2''')

        if (root.tk.call('tk', 'windowingsystem')=='aqua'):
            self.Button2.bind('<Button-2>', lambda e: self.popup2(e))
            self.Button2.bind('<Control-1>', lambda e: self.popup2(e))
        else:
            self.Button2.bind('<Button-3>', lambda e: self.popup2(e))

    @staticmethod
    def popup1(event):
        _bgcolor = 'wheat'  # X11 color: #f5deb3
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#b2c9f4' # Closest X11 color: 'SlateGray2'
        _ana1color = '#eaf4b2' # Closest X11 color: '{pale goldenrod}'
        _ana2color = '#f4bcb2' # Closest X11 color: 'RosyBrown2'
        font10 = "-family {DejaVu Sans Mono} -size 14 -weight normal  " + \
            "-slant roman -underline 0 -overstrike 0"
        Popupmenu1 = Menu(root, tearoff=0)
        Popupmenu1.configure(activebackground="#ffffcd")
        Popupmenu1.configure(background="#dda0dd")
        Popupmenu1.configure(disabledforeground="#b8a786")
        Popupmenu1.add_command(
                activebackground="#f4bcb2",
                activeforeground="#000000",
                background="wheat",
                command=popup_support.this,
                font=font10,
                foreground="#000000",
                label="This")
        Popupmenu1.add_command(
                activebackground="#f4bcb2",
                activeforeground="#000000",
                background="wheat",
                command=popup_support.that,
                font=font10,
                foreground="#000000",
                label="That")
        Popupmenu1.add_separator(
                background="wheat")
        also = Menu(Popupmenu1,tearoff=0)
        Popupmenu1.add_cascade(menu=also,
                activebackground="#f4bcb2",
                activeforeground="#111111",
                background="wheat",
                font=font10,
                foreground="#000000",
                label="Also")
        also.add_command(
                activebackground="#f4bcb2",
                activeforeground="#000000",
                background="wheat",
                command=popup_support.then,
                font=font10,
                foreground="#000000",
                label="Then")
        also.add_command(
                activebackground="#f4bcb2",
                activeforeground="#000000",
                background="wheat",
                command=popup_support.there,
                font=font10,
                foreground="#000000",
                label="There")
        Popupmenu1.post(event.x_root, event.y_root)

    @staticmethod
    def popup2(event):
        _bgcolor = 'wheat'  # X11 color: #f5deb3
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#b2c9f4' # Closest X11 color: 'SlateGray2'
        _ana1color = '#eaf4b2' # Closest X11 color: '{pale goldenrod}'
        _ana2color = '#f4bcb2' # Closest X11 color: 'RosyBrown2'
        font10 = "-family {DejaVu Sans Mono} -size 14 -weight normal  " + \
            "-slant roman -underline 0 -overstrike 0"
        Popupmenu2 = Menu(root, tearoff=0)
        Popupmenu2.configure(activebackground="#ffffcd")
        Popupmenu2.configure(background=_bgcolor)
        Popupmenu2.configure(disabledforeground="#b8a786")
        Popupmenu2.add_command(
                activebackground="#f4bcb2",
                activeforeground="#000000",
                background="plum",
                command=popup_support.how,
                font=font10,
                foreground="#000000",
                label="How")
        Popupmenu2.add_command(
                activebackground="#f4bcb2",
                activeforeground="#000000",
                background="plum",
                command=popup_support.now,
                font=font10,
                foreground="#000000",
                label="Now")
        Popupmenu2.add_separator(
                background="plum")
        browncow = Menu(Popupmenu2,tearoff=0)
        Popupmenu2.add_cascade(menu=browncow,
                activebackground="#f4bcb2",
                activeforeground="#111111",
                background="plum",
                font=font10,
                foreground="#000000",
                label="BrownCow")
        browncow.add_command(
                activebackground="#f4bcb2",
                activeforeground="#000000",
                background="plum",
                command=popup_support.moo,
                font=font10,
                foreground="#000000",
                label="Moo")
        Popupmenu2.post(event.x_root, event.y_root)






if __name__ == '__main__':
    vp_start_gui()



