#############################################################################
# Generated by PAGE version 4.3.1
# in conjunction with Tcl version 8.6
#    Nov 09, 2014 08:42:00 AM


vTcl:font:add_GUI_font font10 \
"-family {DejaVu Sans} -size 16 -weight normal -slant roman -underline 0 -overstrike 0"
set vTcl(actual_gui_bg) wheat
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) wheat
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #b2c9f4
set vTcl(analog_color_p) #eaf4b2
set vTcl(analog_color_m) #f4bcb2
set vTcl(active_fg) #111111
#############################################################################
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top34
    namespace eval ::widgets::$base {
        set set,origin 1
        set set,size 1
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top34 {base} {
    if {$base == ""} {
        set base .top34
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl:toplevel $top -class Toplevel \
        -background wheat -highlightbackground wheat -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x450+650+150; update
    wm maxsize $top 1905 1170
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Called"
    vTcl:DefineAlias "$top" "parms" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure Button -background wheat
    ttk::style configure Button -foreground #000000
    ttk::style configure Button -font font10
    button $top.but34 \
        -activebackground {#f4bcb2} -activeforeground black -background wheat \
        -command lambda:create_called(rt) -disabledforeground {#b8a786} \
        -font font10 -foreground {#000000} -highlightbackground wheat \
        -highlightcolor black -text {Create Clone} 
    vTcl:DefineAlias "$top.but34" "Button1" vTcl:WidgetProc "parms" 1
    button $top.but35 \
        -activebackground {#f4bcb2} -activeforeground black -background wheat \
        -command lambda:master.destroy() -disabledforeground {#b8a786} \
        -font font10 -foreground {#000000} -highlightbackground wheat \
        -highlightcolor black -text Close 
    vTcl:DefineAlias "$top.but35" "Button2" vTcl:WidgetProc "parms" 1
    label $top.lab36 \
        -activebackground {#ffffcd} -activeforeground black -anchor w \
        -background wheat -disabledforeground {#b8a786} -font font10 \
        -foreground {#000000} -highlightbackground wheat \
        -highlightcolor black -text Label -textvariable self.instance 
    vTcl:DefineAlias "$top.lab36" "Label1" vTcl:WidgetProc "parms" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but34 \
        -in $top -x 210 -y 110 -anchor nw -bordermode ignore 
    place $top.but35 \
        -in $top -x 250 -y 350 -anchor nw -bordermode ignore 
    place $top.lab36 \
        -in $top -x 210 -y 220 -width 273 -height 27 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top34

