.PHONY: clean All

All:
	@echo "----------Building project:[ termV01 - Debug ]----------"
	@cd "termV01" && "$(MAKE)" -f  "termV01.mk"
clean:
	@echo "----------Cleaning project:[ termV01 - Debug ]----------"
	@cd "termV01" && "$(MAKE)" -f  "termV01.mk" clean
